---
title: "Assignment 2"
author: "Lukas Unruh, Teije Langelaan, Gidon Quint"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output: 
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(333)
library(lme4)
library(Matrix)
options(digits=3)
```

# Exercise 1
```{r}
fruitfly_data=read.table(file="fruitflies.txt",header=TRUE)
```
## Lukas)
### a)

### b)

### c)

### d)

### e)

## Gid)
### a)

### b)

### c)

### d)

### e)

## TJ)
### a)

### b)

### c)

### d)

### e)


# Exercise 2
```{r}
birthweight_data=read.csv(file="Birthweight.csv",header=TRUE)
```
## Lukas)
### a)

### b)

### c)

### d)

### e)

## Gid)
### a)

### b)

### c)

### d)

### e)

## TJ)
### a)
```{r}
# Assuming birthweight_data is your dataset
summary(birthweight_data)
pairs(~Birthweight + Length + Headcirc + Gestation + mage + mnocig + mheight + mppwt + fage + fedyrs + fnocig + fheight, data=birthweight_data)

# Fit a linear model
TJ_BW <- lm(Birthweight ~ Length + Headcirc + Gestation + mage + mnocig + mheight + mppwt + fage + fedyrs + fnocig + fheight, data=birthweight_data)

# Plot diagnostics for influential points
par(mfrow=c(2,2))
plot(TJ_BW, which=1:4) # Plots for residuals, leverage, etc.

```

### b)

### c)

### d)

### e)

# Exercise 3
```{r}
awards_data=read.table(file="awards.txt",header=TRUE)
```
## Lukas)
### a)

### b)

### c)

## Gid)
### a)

### b)

### c)

## TJ)
### a)

### b)

### c)
